name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
        sudo add-apt-repository ppa:savoury1/ffmpeg4 -y
        sudo add-apt-repository ppa:savoury1/ffmpeg5 -y
        sudo apt update
        sudo apt install ffmpeg
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
