name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install FFMPEG
        run: |
          sudo apt update
          sudo apt install ffmpeg clang curl libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev libavfilter-dev pkg-config -y
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
